# -*- coding: utf-8 -*-
"""Risk Assessment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11_wz2ARAC5q8JDJaaRvDpzKAX0XDX9gN
"""

import streamlit as st
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import json

st.set_page_config(page_title="IoT Camera Risk Assessment", layout="wide")

st.title("📷 IoT Smart Camera Security Risk Assessment")

st.markdown("This app demonstrates a simulation-based security model for analyzing vulnerabilities in smart IoT cameras.")

uploaded_file = st.file_uploader("📤 Upload Nmap/OpenVAS JSON Report", type=["json"])

if uploaded_file:
    report_data = json.load(uploaded_file)
    st.success("✅ Scan data uploaded successfully!")

    # Simulated parsing
    st.subheader("🔎 Sample Vulnerabilities Extracted")
    df = pd.DataFrame([
        {"Vulnerability": "Default Admin Password", "CVE": "CVE-2021-12345", "CVSS": 9.8, "Risk": "Critical"},
        {"Vulnerability": "Outdated Firmware", "CVE": "CVE-2020-6789", "CVSS": 7.5, "Risk": "High"},
        {"Vulnerability": "Unencrypted Video Stream", "CVE": "CVE-2022-4444", "CVSS": 6.2, "Risk": "Medium"},
    ])
    st.dataframe(df)

    st.subheader("🔥 Risk Matrix (Likelihood vs Impact)")
    risk_matrix = pd.DataFrame([
        ["Low", "Medium", "High"],
        ["Medium", "High", "Critical"],
        ["High", "Critical", "Critical"]
    ], index=["Low", "Medium", "High"], columns=["Low", "Medium", "High"])

    fig, ax = plt.subplots()
    sns.heatmap([[1, 2, 3], [2, 3, 4], [3, 4, 5]], annot=risk_matrix.values, cmap="YlOrRd", cbar=False, ax=ax)
    ax.set_xlabel("Impact")
    ax.set_ylabel("Likelihood")
    st.pyplot(fig)

    st.subheader("🛡️ Recommended Mitigations")
    st.markdown("""
    - Change default admin passwords immediately.
    - Apply firmware updates to patch known vulnerabilities.
    - Encrypt video streams using TLS/SSL.
    - Close unused ports and disable Telnet access.
    """)
else:
    st.warning("Upload a JSON scan report to start analysis.")