# -*- coding: utf-8 -*-
"""Risk Assessment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11_wz2ARAC5q8JDJaaRvDpzKAX0XDX9gN
"""

import streamlit as st
import pandas as pd
from io import StringIO

st.title("📷 IoT Smart Camera Risk Report Viewer")

st.subheader("📤 Upload Files")

matrix_file = st.file_uploader("🖼️ Upload Risk Matrix (PNG)", type=["png"])
table_file = st.file_uploader("📄 Upload Risk Assessment Table (CSV)", type=["csv"])
nmap_file = st.file_uploader("📜 Upload Nmap Scan Results (TXT)", type=["txt"])

# Show matrix heatmap
if matrix_file:
    st.image(matrix_file, caption="Risk Heatmap", use_column_width=True)

# Show assessment table
if table_file:
    try:
        df = pd.read_csv(table_file)
        st.subheader("📋 Risk Assessment Table")
        st.dataframe(df)
    except Exception as e:
        st.error(f"Could not read CSV file: {e}")

# Show raw Nmap output
if nmap_file:
    try:
        content = nmap_file.read().decode("utf-8")
        st.subheader("🔍 Nmap Scan Output")
        st.text(content)
    except Exception as e:
        st.error(f"Could not read TXT file: {e}")